icons_format = "{icon}"

[theme]
theme = "native"
[theme.overrides]
idle_bg = "#141414"
idle_fg = "#eae1c7"
good_fg = "#9fa18e"
warning_fg = "#cbb981"
critical_fg = "#7f6969"

[[block]]
block = "custom"
command = ''' fortune '''
interval = 600

[[block]]
block = "apt"

[[block]]
block = "external_ip"
format = " $city $ip "

[icons]
icons = "material-nf"
[icons.overrides]
bat = ["|E|", "|_|", "|=|", "|F|"]
bat_charging = "|^| "

[[block]]
block = "cpu"

[[block]]
block = "temperature"

[[block]]
block = "amd_gpu"

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon root: $available.eng(w:2) "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

# [[block]]
# block = "weather"
# format = " $icon $weather $temp, $wind m/s $direction "
# autolocate = true
# [[block.service]]
# name = "metno"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "
